# Generated by Django 3.2.5 on 2021-07-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210707_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
