# Generated by Django 3.2.5 on 2021-07-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profilemodel_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='unique_key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
