# Generated by Django 3.2.5 on 2021-07-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profilemodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
